"""Backend facade for legal research operations."""

from typing import List

from legal_mcp.domain.legal_research import LegalResearchRequest, LegalResearchResult


def get_backend(country: str, domain: str) -> str:
    """Return backend identifier for the given legal context.

    This is intentionally simple for now and can later route by country/domain
    to dedicated providers or data stores.
    """
    return f"default:{country.lower()}:{domain}"


def run_legal_research(req: LegalResearchRequest) -> List[LegalResearchResult]:
    """Run a minimal legal research query.

    Current implementation returns deterministic placeholder results so that
    contributors can build handlers/tests before integrating real data sources.
    """
    backend_name = get_backend(req.country, req.domain)
    max_items = max(1, min(req.limit, 10))

    base_results = [
        LegalResearchResult(
            title=f"{req.country} {req.domain} overview for: {req.query}",
            source="internal-placeholder://overview",
            summary=(
                f"Starter result generated by {backend_name}. Replace with real "
                "case law/statute search in production."
            ),
        ),
        LegalResearchResult(
            title=f"Key authority candidates: {req.query}",
            source="internal-placeholder://authorities",
            summary="Use this slot to return citations and confidence signals.",
        ),
    ]
    return base_results[:max_items]
